### ISSUE TITLE
Ookeenga launch checklist

### ISSUE THREAD

**Issue by Emman1598** [mgguild/gamevault-frontend#224]
Card

- [ ]  Check if the status is ongoing
- [ ]  Check countdown timer if correct
- [ ]  Check total raised if correct (total raised is the amount of WZRD token sold in BUSD)
- [ ]  Check if OKG for sale if 1,250,000 OKG
- [ ]  Check if buying coin is BUSD
- [ ]  Check if distribution type is correct. (In Ookeenga it is Vesting)

Individual Project Page

- [ ] Check status if ongoing
- [ ]  Check social media links if correct
- [ ]  Check countdown timer if correct
- [ ]  Check percentage of tokens sold ( percentage = token sold / token for sale)
- [ ]  Check total raised if correct (total raised is the amount of OKG token sold in BUSD)
- [ ]  Check token price. ( 1 OKG = $0.04)
- [ ]  Check tokens sold if correct
- [ ]  User should not be able to purchase more than their max allocation.
- [ ]  My allocation shows the number of tokens bought by the user
- [ ]  If users already bought all of their allocations, the purchase button should be disabled
- [ ]  Sold Out button should appear if there are no more tokens available.
- [ ]  Non whitelisted addresses should not be able to participate

Purchase Modal

- [ ]  Check if Price per BUSD is correct
- [ ]  When clicking Max button, it should input the user's remaining allocation
- [ ]  My allocation shows the number of tokens bought by the user
- [ ]  After swapping/buying, tokens bought by the user should reflect on My Allocation without having to refresh the page
- [ ]  Toast should appear correctly based on what the user's action performed.
- [ ]  Transaction should not proceed if the user rejected it on MetaMask
- [ ]  Remaining BUSD should tally with Remaining OKG
